// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo18sSSPznN-Mp0DQ-PVKzDon7zVDed08',
    appId: '1:1062119518637:web:cef3c5f836534c71a4f124',
    messagingSenderId: '1062119518637',
    projectId: 'zxzihgr40xy51ft3zzq346fxysed2e',
    authDomain: 'zxzihgr40xy51ft3zzq346fxysed2e.firebaseapp.com',
    storageBucket: 'zxzihgr40xy51ft3zzq346fxysed2e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkpw3OUiAbhf8u4MaHnr6qk6SzqSJmEiQ',
    appId: '1:1062119518637:android:8984d4c3f03b5bfca4f124',
    messagingSenderId: '1062119518637',
    projectId: 'zxzihgr40xy51ft3zzq346fxysed2e',
    storageBucket: 'zxzihgr40xy51ft3zzq346fxysed2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMST4aLygVdp58iRi5oQ4zUM-oFpeq_pY',
    appId: '1:1062119518637:ios:9db4ba7fa84dd0d0a4f124',
    messagingSenderId: '1062119518637',
    projectId: 'zxzihgr40xy51ft3zzq346fxysed2e',
    storageBucket: 'zxzihgr40xy51ft3zzq346fxysed2e.firebasestorage.app',
    iosBundleId: 'com.awesomeorg.uprush',
  );
}
